In [4]:
import pandas as pd

In [5]:
df = pd.read_clipboard(header=None)
df.columns = ['Subportfolio', 'Year', 'Stat', 'NCF','REC','IRV']
df

       Subportfolio  Year  Stat       NCF         REC     IRV
0           AMER_RE  2024   P75     82.82  14351025.0   -5.77
1           AMER_RE  2024   P25     87.54  14193193.0   -6.17
2           AMER_RE  2024  Mean     85.13  14271462.0   -5.97
3           AMER_RE  2024    P5     90.57  14097520.0   -6.42
4           AMER_RE  2024   P95     80.30  14429044.0   -5.57
..              ...   ...   ...       ...         ...     ...
170  TOTALPORTFOLIO  2030  Mean  12390.46 -59438268.0  208.46
171  TOTALPORTFOLIO  2030   P95  10889.86 -59135464.0  184.15
172  TOTALPORTFOLIO  2030   P75  12063.70 -59289908.0  203.47
173  TOTALPORTFOLIO  2030   P25  12781.01 -59613368.0  214.40
174  TOTALPORTFOLIO  2030    P5  13614.39 -59724980.0  227.95

[175 rows x 6 columns]

In [6]:
#pivot the df so that the years are the columns and stats and subportfolio are the rows
df_pivot = df.pivot(index=['Subportfolio', 'Stat'], columns='Year', values='NCF')
df_pivot.to_clipboard()
df_pivot

Year                   2024     2025     2026     2027      2028      2029  \
Subportfolio   Stat
AMER_RE        Mean   85.13   287.05   340.85   402.36    419.51    445.88
               P25    87.54   368.07   595.29   779.01    959.49   1148.02
               P5     90.57   470.70   764.35  1106.04   1460.04   1625.37
               P75    82.82   207.12   104.85   175.63    -42.27   -209.01
               P95    80.30    60.96  -317.58  -751.53  -1378.73  -1524.12
APAC_RE        Mean   13.05    20.26    38.63    53.24     58.50     71.96
               P25    13.09    24.39    52.84    75.61     90.30     79.49
               P5     13.17    29.74    61.48    90.24    103.46     84.61
               P75    13.01    15.53    28.14    42.65     48.99     66.29
               P95    12.94    11.74    11.08    13.47    -11.28     55.24
EMEA_RE        Mean   12.31    17.11    -0.63     9.35     15.74    -46.81
               P25    13.63    81.94   167.81   270.92    261.73    276.47
               P5     15.72   157.29   276.78   404.07    427.78    413.49
               P75    11.00   -33.51   -85.70  -208.95   -177.31   -132.38
               P95     9.33  -200.40  -449.72  -673.26   -522.27  -1101.29
RE             Mean  110.50   324.41   378.85   464.94    493.74    471.03
               P25   112.90   428.10   738.60   896.93   1122.10   1491.20
               P5    118.15   600.80   948.72  1291.63   1771.97   1862.64
               P75   107.60   229.05   159.78   214.68    156.98   -340.13
               P95   104.07    48.58  -462.91  -956.22  -1481.33  -2018.05
TOTALPORTFOLIO Mean  146.07  4286.03  6377.22  8809.01  10675.19  11825.82
               P25   148.48  4376.27  6571.61  9212.80  11176.35  12294.08
               P5    153.71  4434.30  6759.39  9546.45  11581.95  12977.80
               P75   143.18  4206.48  6224.63  8499.18  10314.75  11488.55
               P95   139.56  4076.04  5775.81  7941.64   9218.16  10553.21

Year                     2030
Subportfolio   Stat
AMER_RE        Mean    446.19
               P25    1232.48
               P5     1747.82
               P75     150.95
               P95   -2328.66
APAC_RE        Mean     64.98
               P25      73.10
               P5       76.18
               P75      58.45
               P95      39.43
EMEA_RE        Mean     70.08
               P25     338.03
               P5      487.68
               P75     -41.14
               P95    -754.45
RE             Mean    581.26
               P25    1616.36
               P5     2072.34
               P75     267.42
               P95   -2251.03
TOTALPORTFOLIO Mean  12390.46
               P25   12781.01
               P5    13614.39
               P75   12063.70
               P95   10889.86